name: CI

on:
  - push

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name : secret file
        run : echo 'apiVersion: v1 \n
kind: Secret \n
metadata: \n
  name: fdic-secret-production \n
data: \n
  API_URL: aHR0cHM6Ly9mZGljLWFwaS5yZWFkeS1yb2JvdGljcy5jbG91ZC9hcGkvdjE= \n
  ACCESS_TOKEN_KEY: YWNjZXNzX3Rva2Vu \n ' >> secret.yaml
      - name : read secret
        run : cat secret.yaml

      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f deployment.yaml -n githubaction
